### ISSUE TITLE
Social Media icon missing from filter bar

### ISSUE THREAD

**Issue by ohnno** [ohnno/Brosa#29]
Location: Category Page
Browser: Firefox
OS: OS X Mavericks
Screen: Laptop

One of the social media icons does not load for me.

**Comment by limcolin** [comment]
fixed but i need to ask shaz why 'shop by' btn is causing sharing panel to disappear

**Comment by limcolin** [comment]
REMINDER TO SELF: SOCIAL MEDIA ICONS MISSING FROM FOOTER

**Comment by limcolin** [comment]
REMINDER TO SELF: MASTERCARD AMEX

**Comment by ohnno** [comment]
Hey the instagram icon is still missing for me on all browsers.
